version: "3.9"
services:

  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    env_file:
      - .env
    volumes:
      - ./projects/:/config/workspace
    working_dir: /caddy-code-server
    restart: unless-stopped
    logging:
      driver: "journald"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on: [code-server]
    logging:
      driver: "journald"

volumes:
  caddy_data:
  caddy_config:
