version: "3.3"
services:

  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=${DOMAIN}
    volumes:
      - /home/code-server:/config
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [code-server]

volumes:
  caddy_data:
  caddy_config:
